#!/usr/bin/env bash

if [ -z "VERSION_LOG" ]; then
    VERSION_LOG=`mktemp`
    trap "{ rm -f $VERSION_LOG; }" EXIT
fi

foreach-get-version >> $VERSION_LOG
git submodule foreach -q gradle-set-dependencies $VERSION_LOG
get-version >> $VERSION_LOG
gradle-set-dependencies $VERSION_LOG
