#!/usr/bin/env bash

gradle-get-dependencies | while IFS=$'\t' read -r -a source
do
    cat $1 | while IFS=$'\t' read -r -a target
    do
        for suffix in "" "-test";
        do
            if [[ "${source[0]}" == "${target[0]}"  && \
                  "${source[1]}" == "${target[1]}${suffix}" ]];
            then
                if [[ "${source[2]}" != "${target[2]}" ]];
                then
                   echo "Updating ${target[1]}${suffix} from ${source[2]} to ${target[2]}"
                   PATTERN="s"
                   PATTERN="$PATTERN/${source[0]}:${source[1]}:${source[2]}"
                   PATTERN="$PATTERN/${target[0]}:${target[1]}${suffix}:${target[2]}/"
                   sed -i $PATTERN build.gradle
                else
                   echo "Up-to-date: ${target[1]}${suffix}"
                fi
            fi
        done
    done
done
