#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
$DIR/gradle-get-dependencies | while IFS=$'\t' read -r -a source
do
    cat $1 | while IFS=$'\t' read -r -a target
    do
        if [[ "${source[0]}" == "${target[0]}"  && \
              "${source[1]}" == "${target[1]}" ]];
        then
            if [[ "${source[2]}" != "${target[2]}" ]];
            then
               echo "Updating ${target[1]}"
               PATTERN="s"
               PATTERN="$PATTERN/${source[0]}:${source[1]}:${source[2]}"
               PATTERN="$PATTERN/${target[0]}:${target[1]}:${target[2]}/"
               sed -ie $PATTERN build.gradle
            else
               echo "Up-to-date: ${target[1]}"
            fi
        fi
    done
done
