#!/usr/bin/env bash

gradle-get-version | while IFS=$'\t' read -r -a source
do
    cat $1 | while IFS=$'\t' read -r -a target
    do
        if [[ "${source[0]}" == "${target[0]}"  && \
              "${source[1]}" == "${target[1]}" ]];
        then
            if [[ "${source[2]}" != "${target[2]}" ]];
            then
               echo "Updating ${target[1]}"
               PATTERN="s/^version = '${source[2]}'/version = '${target[2]}'/"
               PATTERN=$(echo $PATTERN | tr \' \")
               sed -ie "$PATTERN" build.gradle
            else
               echo "Up-to-date: ${target[1]}"
            fi
        fi
    done
done
