#!/usr/bin/env python
import sys
import json
import requests
import collections
import argparse

parser = argparse.ArgumentParser()
parser.add_argument("--url", default="https://ci.openmicroscopy.org/api/json")
ns = parser.parse_args()

try:
    r = requests.get(ns.url)
    all = json.loads(r.content)
    errors = list()
    jobs = all["jobs"]
    jobs.sort(lambda a,b: cmp(a["name"], b["name"]))
    results = collections.defaultdict(list)
    for job in jobs:
        u = job["url"]
        c = job["color"]
        results[c].append(u)
        print "%10s\t%s" % (c, u)
        if c in ("red", "yellow"):
            errors.append(u)
    # print results.keys()
    sys.exit(len(errors))
except KeyboardInterrupt:
    sys.exit(-1)
