#!/usr/bin/env bash

MERGE_OPTIONS=${MERGE_OPTIONS:-"-vvv --no-ask --reset"}
STATUS=${STATUS:-"success-only"}
PUSH_BRANCH=${PUSH_BRANCH:-"merge"}
BASE_BRANCH=${BASE_BRANCH:-"master"}
BASE_REPO=${BASE_REPO:-$(basename $PWD).git}
GIT_HOST=${GIT_HOST:-}
GIT_USER=${GIT_USER:-$(git config github.user)}

# scc can only push to GitHub
if [ -n "$GIT_HOST" ]; then
    SCC_PUSH=
else
    GIT_HOST=git@github.com
    SCC_PUSH="--push $PUSH_BRANCH"
fi


DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
PATH=$DIR:$PATH

set -e
set -u

echo "Merge base repository (no submodule updates)"
scc merge $MERGE_OPTIONS --shallow $BASE_BRANCH

# Update any changed submodules
git submodule sync
git submodule update --remote --recursive

REPO_CONFIG=
echo -n "Merge all submodules"
if [ -f "scripts/repositories.yml" ]; then
    echo " using repository configuration:"
    cat "scripts/repositories.yml"
    REPO_CONFIG="--repository-config=repositories.yml"
fi
scc merge $REPO_CONFIG $MERGE_OPTIONS -S $STATUS --update-gitmodules $SCC_PUSH $BASE_BRANCH

echo "Update component versions"
foreach-set-dependencies

echo "Commit all component version changes"
git submodule foreach "git add -u"
git submodule foreach "git commit -m 'Update component versions' || true"

echo "Push all branches"
git submodule foreach "git push -f $GIT_HOST:$GIT_USER/"'${path}.git'" HEAD:refs/heads/$PUSH_BRANCH"

echo "Commit all component version changes"
git add -u
git commit -m 'Update component versions' || true

git push -f $GIT_HOST:$GIT_USER/${BASE_REPO} HEAD:refs/heads/$PUSH_BRANCH
